/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as PedidosIndexRouteImport } from './routes/pedidos.index'
import { Route as PedidosOrderIdRouteImport } from './routes/pedidos.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosIndexRoute = PedidosIndexRouteImport.update({
  id: '/pedidos/',
  path: '/pedidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosOrderIdRoute = PedidosOrderIdRouteImport.update({
  id: '/pedidos/$orderId',
  path: '/pedidos/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/mapa': typeof MapaRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/mapa': typeof MapaRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/pedidos': typeof PedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/carrinho': typeof CarrinhoRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/mapa': typeof MapaRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos/$orderId': typeof PedidosOrderIdRoute
  '/pedidos/': typeof PedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/mapa'
    | '/loja/$slug'
    | '/pedidos/$orderId'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/mapa'
    | '/loja/$slug'
    | '/pedidos/$orderId'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/carrinho'
    | '/categorias'
    | '/checkout'
    | '/mapa'
    | '/loja/$slug'
    | '/pedidos/$orderId'
    | '/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  CarrinhoRoute: typeof CarrinhoRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRoute
  MapaRoute: typeof MapaRoute
  LojaSlugRoute: typeof LojaSlugRoute
  PedidosOrderIdRoute: typeof PedidosOrderIdRoute
  PedidosIndexRoute: typeof PedidosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/': {
      id: '/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof PedidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos/$orderId': {
      id: '/pedidos/$orderId'
      path: '/pedidos/$orderId'
      fullPath: '/pedidos/$orderId'
      preLoaderRoute: typeof PedidosOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  CarrinhoRoute: CarrinhoRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRoute,
  MapaRoute: MapaRoute,
  LojaSlugRoute: LojaSlugRoute,
  PedidosOrderIdRoute: PedidosOrderIdRoute,
  PedidosIndexRoute: PedidosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
